/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_dynamodb_all_tables_region": "eu-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "UserListTable-dev",
            "region": "eu-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-2:9b0821a5-1b85-4a16-b66f-5f0abf5e3ec3",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_BOPVgzvgY",
    "aws_user_pools_web_client_id": "3c2jtuf26rpo9jcj6rv3ol5qnc",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "UserApi",
            "endpoint": "https://dlomsc9lt0.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ]
};


export default awsmobile;
